### ISSUE TITLE
Dynamically update text field

### ISSUE THREAD

**Issue by thebytedoc** [humberry/ui-tutorial#35]
I’m new to python & pythonista, but I’m really enjoying it. 
	So my issue; I’m trying to update a text field with a running elapsed timer. I attempted to use a software interrupt (signal module) with no success. It seems to me the ui is constantly polling for actions, so I should think I could tap into that, just haven’t found the secret yet. Any hints are appreciated.

**Comment by humberry** [comment]
Have you tried to decorated your method with @ui.in_background? Pythonista Manual > UI > About Actions and Delegates

**Comment by thebytedoc** [comment]
So I found the answer in the form of a custom view and utilizing the update_interval & update method. This was the exact process I needed.
